POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Implc3NpY2EiLCJpZCI6IjVlZThjZTBlODQ3NjI1MDhhMGRkODM0MSIsImlhdCI6MTU5MjQwNTYyN30.ZQlFFbd2-fU7RdsMhsloDPnjBIH7SDBJ2bnSP9D8UEk

{
    "title" : "test 4 title",
    "author" : "test 4 author",
    "url" : "test 4 url",
    "likes" : "4"
}